name: Ubuntu

on:
    push:
        branches: [main]
    pull_request:
    workflow_dispatch:

concurrency:
    group: "${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.ref_name }}"
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Check environment
              run: |
                  echo "Node.js version: $(node -v)"
                  echo "Npm version: $(npm -v)"
                  echo "Yarn version: $(yarn -v)"

            - name: Install
              run: yarn install --network-concurrency 1 --frozen-lockfile

            - name: Package
              run: npm run package

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: Binaries
                  path: |
                      build/binaries/LEEDEX*
                      build/release-checksums-*
