name: Ubuntu

on:
    push:
        branches: [main]
        tags: [v*]
    pull_request:
    workflow_dispatch:

concurrency:
    group: "${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.ref_name }}"
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Check environment
              run: |
                  echo "Node.js version: $(node -v)"
                  echo "Npm version: $(npm -v)"
                  echo "Yarn version: $(yarn -v)"

            - name: Install
              run: yarn install --frozen-lockfile

            - name: Build
              run: yarn run build

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: site
                  path: build/dist
                  retention-days: 1

    release:
        if: contains(github.ref, 'refs/tags/v')
        runs-on: ubuntu-20.04
        needs: build
        steps:
            - uses: actions/download-artifact@v3
              with:
                  name: site
                  path: site

            - name: Package binary into archive
              run: |
                  tar -czvf leedex-ui.tgz site

            - name: Calculate SHA256 hash
              run: |
                  sha256sum leedex-ui.tgz | cut -d ' ' -f1 > leedex-ui.tgz.sha256.txt

            - uses: softprops/action-gh-release@v1
              with:
                  files: |
                      leedex-ui.tgz
                      leedex-ui.tgz.sha256.txt
